services:
  onboarding-api:
    build:
      context: projects/backend
      dockerfile: onboarding-api/docker/Dockerfile
      target: development
      args:
        - BASE_IMAGE=${ONBOARDING_API_BASE_IMAGE}
    environment:
      - DEBUG=True
    ports:
      - "8080:80"
    volumes:
      - ${DEPLOY_DIR}/projects/backend/onboarding-api/src:/opt/pysetup/src
      - ${DEPLOY_DIR}/projects/backend/onboarding-api/tests:/opt/pysetup/tests
      - ${DEPLOY_DIR}/projects/backend/onboarding-api/alembic:/opt/pysetup/alembic

  onboarding-db:
    ports:
      - "5551:5432"
