services:
  onboarding-web-app:
    build:
      target: development
    ports:
      - "8083:80"
    volumes:
      - ${DEPLOY_DIR}/projects/frontend/packages/onboarding:/tmp/packages/onboarding
      - ${DEPLOY_DIR}/projects/frontend/packages/shared:/tmp/packages/shared
      - ${DEPLOY_DIR}/projects/frontend/lerna.json:/tmp/lerna.json
      - ${DEPLOY_DIR}/projects/frontend/package.json:/tmp/package.json
      - ${DEPLOY_DIR}/projects/frontend/package-lock.json:/tmp/package-lock.json
      - ${DEPLOY_DIR}/projects/frontend/tsconfig.json:/tmp/tsconfig.json

  board-web-app:
    build:
      target: development
    ports:
      - "8084:80"
    volumes:
      - ${DEPLOY_DIR}/projects/frontend/packages/board:/tmp/packages/board
      - ${DEPLOY_DIR}/projects/frontend/packages/shared:/tmp/packages/shared
      - ${DEPLOY_DIR}/projects/frontend/lerna.json:/tmp/lerna.json
      - ${DEPLOY_DIR}/projects/frontend/package.json:/tmp/package.json
      - ${DEPLOY_DIR}/projects/frontend/package-lock.json:/tmp/package-lock.json
      - ${DEPLOY_DIR}/projects/frontend/tsconfig.json:/tmp/tsconfig.json

  onboarding-api:
    build:
      target: development
    environment:
      - DEBUG=True
    ports:
      - "8080:80"
    volumes:
      - ${DEPLOY_DIR}/projects/backend/onboarding-api/src:/opt/pysetup/src
      - ${DEPLOY_DIR}/projects/backend/onboarding-api/tests:/opt/pysetup/tests
      - ${DEPLOY_DIR}/projects/backend/onboarding-api/alembic:/opt/pysetup/alembic

  board-api:
    build:
      target: development
    environment:
      - DEBUG=True
    ports:
      - "8081:80"
    volumes:
      - ${DEPLOY_DIR}/projects/backend/board-api/src:/opt/pysetup/src
      - ${DEPLOY_DIR}/projects/backend/board-api/tests:/opt/pysetup/tests

  board-events-db:
    ports:
      - "8123:8123"

  onboarding-db:
    ports:
      - "5551:5432"
#  minio:
#    ports:
#      - "9900:9000"
