"""Initial database

Revision ID: 7b36f680eb80
Revises: 
Create Date: 2024-10-13 11:31:10.973343+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b36f680eb80'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blob',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('s3_link', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('blob_pkey'))
    )
    op.create_table('board',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('board_pkey'))
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False, unique=True),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey'))
    )
    op.create_table('board_step',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.SmallInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('text', sa.String(length=4096), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('index', sa.SmallInteger(), nullable=False),
    sa.Column('board_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['board_id'], ['board.id'], name=op.f('board_step_board_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('board_step_pkey'))
    )
    op.create_table('board_step_blob',
    sa.Column('board_step_id', sa.Uuid(), nullable=False),
    sa.Column('blob_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['blob_id'], ['blob.id'], name=op.f('board_step_blob_blob_id_fkey')),
    sa.ForeignKeyConstraint(['board_step_id'], ['board_step.id'], name=op.f('board_step_blob_board_step_id_fkey'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board_step_blob')
    op.drop_table('board_step')
    op.drop_table('user')
    op.drop_table('board')
    op.drop_table('blob')
    # ### end Alembic commands ###
